<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/localhost" />
    <meta charset="UTF-8" />
    <title>Evidence pojištěných</title>
    <meta name="description" content="evidence pojištěných osob" />
    <meta name="keywords" content="evidence, pojištění" />
    <link rel="stylesheet" href="../style.css" type="text/css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC:wght@300&family=Poppins&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        
        <h1>Evidence pojištěnců</h1>
        
    </header>
    
    <!-- Inserting messages to the view -->
    
    <?php if (!empty($messages['positive'])): ?>
        <?php foreach ($messages['positive'] as $message): ?>
            <p class="positive-message"><?= $message ?></p>
        <?php endforeach; ?>
    <?php endif; ?>
            
    <?php if (!empty($messages['negative'])): ?>
        <?php foreach ($messages['negative'] as $message): ?>
            <p class="negative-message"><?= $message ?></p>
        <?php endforeach; ?>
    <?php endif; ?>
        
    <article class="container">
        
        <h2>Výpis pojištěnců</h2>
        
        <!-- Rendering a view of all insurees stored in database -->
        
        <?php if (!empty($allInsured)): ?>
            <table class="table">
                <tr>
                    <th>Jméno</th>
                    <th>Příjmení</th>
                    <th>Věk</th>
                    <th>Telefon</th>
                </tr>
                <?php foreach ($allInsured as $insured): ?>
                    <tr>
                        <td><?php echo $insured['name'] ?></td>
                        <td><?php echo $insured['surname'] ?></td>
                        <td><?php echo $insured['age'] ?></td>
                        <td><?php echo $insured['phone_number'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php else: ?>
            <p>Nenašli jsme žádné pojištěné osoby</p>
        <?php endif; ?>
    </article>
    
    <article class="container">
        
        <h2 id="secondHeader">Vytvoření nového pojištěnce</h2>
        
        <!-- Form for inserting new insurees -->
        
        <form method="post">
            
            <div class="form-group">
                <label for="name">Jméno:</label>
                <input type="text" name="name" id="name">
            </div>
            
            <div class="form-group">
                <label for="surname">Příjmení:</label>
                <input type="text" name="surname" id="surname">
            </div>
            
            <div class="form-group">
                <label for="age">Věk:</label>
                <input type="number" name="age" id="age">
            </div>
            
            <div class="form-group">
                <label for="phone_number">Telefon:</label>
                <input type="text" name="phone_number" id="phone_number">
            </div>
            
            <div class="form-group">
                <input type="submit" value="Odešli">
            </div>
            
        </form>
    </article>    
</body>
</html>
